Collecting pip==23.1
  Using cached pip-23.1-py3-none-any.whl.metadata (4.1 kB)
Collecting wheel==0.43.0
  Using cached wheel-0.43.0-py3-none-any.whl.metadata (2.2 kB)
Using cached pip-23.1-py3-none-any.whl (2.1 MB)
Using cached wheel-0.43.0-py3-none-any.whl (65 kB)
Installing collected packages: wheel, pip
  Attempting uninstall: pip
    Found existing installation: pip 24.0
    Uninstalling pip-24.0:
      Successfully uninstalled pip-24.0
Successfully installed pip-23.1 wheel-0.43.0

[notice] A new release of pip is available: 23.1 -> 24.1.2
[notice] To update, run: python -m pip install --upgrade pip
Collecting opt-einsum==3.3.0
  Using cached opt_einsum-3.3.0.tar.gz (73 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [31 lines of output]
      /tmp/tmp.DBKOTI6SRQ/pip-install-me_zb0t6/opt-einsum_9c660327873b4265adbeb781e8414a59/versioneer.py:421: SyntaxWarning: invalid escape sequence '\s'
        LONG_VERSION_PY['git'] = '''
      Traceback (most recent call last):
        File "/tmp/tmp.DBKOTI6SRQ/tmpylfn7p37/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/tmp/tmp.DBKOTI6SRQ/tmpylfn7p37/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/tmp.DBKOTI6SRQ/tmpylfn7p37/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/tmp.DBKOTI6SRQ/pip-build-env-vp987oqk/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/tmp.DBKOTI6SRQ/pip-build-env-vp987oqk/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "/tmp/tmp.DBKOTI6SRQ/pip-build-env-vp987oqk/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 497, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/tmp.DBKOTI6SRQ/pip-build-env-vp987oqk/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 17, in <module>
        File "/tmp/tmp.DBKOTI6SRQ/pip-install-me_zb0t6/opt-einsum_9c660327873b4265adbeb781e8414a59/versioneer.py", line 1480, in get_version
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "/tmp/tmp.DBKOTI6SRQ/pip-install-me_zb0t6/opt-einsum_9c660327873b4265adbeb781e8414a59/versioneer.py", line 1412, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/tmp.DBKOTI6SRQ/pip-install-me_zb0t6/opt-einsum_9c660327873b4265adbeb781e8414a59/versioneer.py", line 342, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
WARNING: There was an error checking the latest version of pip.
Traceback (most recent call last):
  File "/nix/store/h71zwamfrx3sah2bv18scmm16a3zk6w7-python3.12-fetch-pip-metadata/bin/.fetch_pip_metadata-wrapped", line 9, in <module>
    sys.exit(fetch_pip_metadata())
             ^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/h71zwamfrx3sah2bv18scmm16a3zk6w7-python3.12-fetch-pip-metadata/lib/python3.12/site-packages/fetch_pip_metadata/__init__.py", line 78, in fetch_pip_metadata
    subprocess.run(
  File "/nix/store/z7xxy35k7620hs6fn6la5fg2lgklv72l-python3-3.12.4/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/tmp/tmp.DBKOTI6SRQ/tmpylfn7p37/.venv/bin/pip', 'install', '--dry-run', '--ignore-installed', '--no-binary', 'opt-einsum', '--progress-bar', 'off', '--report', '/tmp/tmp.DBKOTI6SRQ/tmpylfn7p37/report.json', 'opt-einsum==3.3.0']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/nix/store/0j2mh7my2mk8lknrps2qhgm6jsfkigz3-refresh/bin/refresh", line 40, in <module>
    lock_data = run_refresh_scripts(refresh_scripts)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/0j2mh7my2mk8lknrps2qhgm6jsfkigz3-refresh/bin/refresh", line 36, in run_refresh_scripts
    refresh_scripts[name] = run_refresh_script(value["script"])
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/0j2mh7my2mk8lknrps2qhgm6jsfkigz3-refresh/bin/refresh", line 22, in run_refresh_script
    subprocess.run(
  File "/nix/store/z7xxy35k7620hs6fn6la5fg2lgklv72l-python3-3.12.4/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/nix/store/4qi7vs8n5xxiaxkcwyl74nq0kq4nfsc7-script.sh']' returned non-zero exit status 1.
